### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by aGeftw** [chrisss404/check-mk-arm#1]
Hi, can you help? with dpkg -i check_mk-file and apt-get -f install i cannot install check_mk. he delete the files, with apt-get -f install.

**Comment by chrisss404** [comment]
Hi, I can not reproduce your issue, here is what I am doing. Maybe this helps.

### OS version

    root@raspberry:/home/someone# cat /etc/*-release
    PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
    NAME="Raspbian GNU/Linux"
    VERSION_ID="9"
    VERSION="9 (stretch)"
    ID=raspbian
    ID_LIKE=debian
    HOME_URL="http://www.raspbian.org/"
    SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
    BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

### Install check_mk and dependencies

    root@raspberry:/home/someone# dpkg -i check-mk-raw-1.4.0p33_0.stretch_armhf.deb
    Selecting previously unselected package check-mk-raw-1.4.0p33.
    (Reading database ... 82480 files and directories currently installed.)
    Preparing to unpack check-mk-raw-1.4.0p33_0.stretch_armhf.deb ...
    Unpacking check-mk-raw-1.4.0p33 (0.stretch) ...
    dpkg: dependency problems prevent configuration of check-mk-raw-1.4.0p33:
     check-mk-raw-1.4.0p33 depends on libnet-snmp-perl; however:
      Package libnet-snmp-perl is not installed.
     check-mk-raw-1.4.0p33 depends on libpango1.0-0; however:
      Package libpango1.0-0 is not installed.
     check-mk-raw-1.4.0p33 depends on libsnmp-perl; however:
      Package libsnmp-perl is not installed.
     check-mk-raw-1.4.0p33 depends on rpm; however:
      Package rpm is not installed.
     check-mk-raw-1.4.0p33 depends on php; however:
      Package php is not installed.
     check-mk-raw-1.4.0p33 depends on php-cgi; however:
      Package php-cgi is not installed.
     check-mk-raw-1.4.0p33 depends on php-cli; however:
      Package php-cli is not installed.
     check-mk-raw-1.4.0p33 depends on php-gd; however:
      Package php-gd is not installed.
     check-mk-raw-1.4.0p33 depends on php-mcrypt; however:
      Package php-mcrypt is not installed.
     check-mk-raw-1.4.0p33 depends on php-sqlite3; however:
      Package php-sqlite3 is not installed.
     check-mk-raw-1.4.0p33 depends on php-pear; however:
      Package php-pear is not installed.
     check-mk-raw-1.4.0p33 depends on lcab; however:
      Package lcab is not installed.
    
    dpkg: error processing package check-mk-raw-1.4.0p33 (--install):
     dependency problems - leaving unconfigured
    Processing triggers for systemd (232-25+deb9u2) ...
    Processing triggers for man-db (2.7.6.1-2) ...
    Errors were encountered while processing:
     check-mk-raw-1.4.0p33
    root@raspberry:/home/someone# apt-get -f install
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    Correcting dependencies... Done
    The following additional packages will be installed:
      debugedit lcab libapache2-mod-php7.0 libnet-snmp-perl libpango1.0-0 libpangox-1.0-0 librpm3 librpmbuild3 librpmio3 librpmsign3
      libsnmp-perl php php-cgi php-common php-gd php-mcrypt php-pear php-sqlite3 php-xml php7.0 php7.0-cgi php7.0-cli php7.0-common php7.0-gd
      php7.0-json php7.0-mcrypt php7.0-opcache php7.0-readline php7.0-sqlite3 php7.0-xml rpm rpm-common rpm2cpio
    Suggested packages:
      rpm-i18n cabextract libcrypt-des-perl alien elfutils rpmlint rpm2html
    The following NEW packages will be installed:
      debugedit lcab libapache2-mod-php7.0 libnet-snmp-perl libpango1.0-0 libpangox-1.0-0 librpm3 librpmbuild3 librpmio3 librpmsign3
      libsnmp-perl php php-cgi php-common php-gd php-mcrypt php-pear php-sqlite3 php-xml php7.0 php7.0-cgi php7.0-cli php7.0-common php7.0-gd
      php7.0-json php7.0-mcrypt php7.0-opcache php7.0-readline php7.0-sqlite3 php7.0-xml rpm rpm-common rpm2cpio
    0 upgraded, 33 newly installed, 0 to remove and 0 not upgraded.
    1 not fully installed or removed.
    Need to get 3,854 kB/15.2 MB of archives.
    After this operation, 33.0 MB of additional disk space will be used.
    Do you want to continue? [Y/n] y

### Start using installed check_mk

    root@raspberry:/home/someone# omd version
    OMD - Open Monitoring Distribution Version 1.4.0p33.cre
    root@raspberry:/home/someone# ls -al /opt/omd/
    total 20
    drwxr-xr-x 5 root root 4096 May 20 10:39 .
    drwxr-xr-x 4 root root 4096 May 20 10:39 ..
    drwxr-xr-x 2 root root 4096 May 20 10:50 apache
    drwxr-xr-x 2 root root 4096 May 20 10:39 sites
    drwxr-xr-x 3 root root 4096 May 20 10:50 versions

If you still have issues installing the deb package, this might help: https://unix.stackexchange.com/questions/159094/how-to-install-a-deb-file-by-dpkg-i-or-by-apt
