### ISSUE TITLE
Raspberry self-check "OMD %sitename% performance" crashes on 1.6.0p5/Buster

### ISSUE THREAD

**Issue by donald2612** [chrisss404/check-mk-arm#16]
Just tried the sources on latest Buster release, and added the monitoring host itself, after installing the agent-package.

It crashes on that check 

"OMD %sitename% performance" 

with 

"ValueError (invalid literal for int() with base 10: '')" 

Other checks run fine though. That points to something wrong with the python-version, but I don't really know.

Any hints?

**Comment by chrisss404** [comment]
Hi donald,

thank you for reporting this issue.

I could identify the problem and can suggest two ways to solve it.

* either edit the file `/omd/sites/health/share/check_mk/checks/livestatus_status` as follows

        -    if cert_valid_until is not None:
        +    if cert_valid_until is not None and cert_valid_until != "":


* or wait for the next relase

HTH & BR
Christian

**Comment by donald2612** [comment]
perfect solution - thanks Chris!

**Comment by chrisss404** [comment]
Has been fixed upstream: https://checkmk.de/check_mk-werks.php?werk_id=10632
