### ISSUE TITLE
Ubuntu 18.04 LTS support?

### ISSUE THREAD

**Issue by Ch-Fr** [chrisss404/check-mk-arm#17]
Would it be possible to provide Ubuntu 18.04 LTS package for ARM? That would be really great!

Thanks!

**Comment by chrisss404** [comment]
I don't think that I am able to do this.

However, if you provide a little more information like where did you get your version of Ubuntu 18.04 LTS from and what errors did you encounter when trying to install the debian package, I can take a look.

BR
Christian
