### ISSUE TITLE
get it work witch stretch

### ISSUE THREAD

**Issue by flix87** [chrisss404/check-mk-arm#2]
I added under this lines:
cp packages/snap7/snap7-full-${SNAP7_VERSION}/build/unix/arm_v6_linux.mk packages/snap7/snap7-full-${SNAP7_VERSION}/build/unix/armv6l_linux.mk
ln -s arm_v6-linux packages/snap7/snap7-full-${SNAP7_VERSION}/build/bin/armv6l-linux
this two lines:
cp packages/snap7/snap7-full-${SNAP7_VERSION}/build/unix/arm_v7_linux.mk packages/snap7/snap7-full-${SNAP7_VERSION}/build/unix/armv7l_linux.mk
ln -s arm_v7-linux packages/snap7/snap7-full-${SNAP7_VERSION}/build/bin/armv7l-linux

so get it work witch stretch.
May this helps someone

**Comment by chrisss404** [comment]
added your improvement
