### ISSUE TITLE
Can I use it in Docker (on HypriotOS) and if yes, how?

### ISSUE THREAD

**Issue by Kruemmelspalter** [chrisss404/check-mk-arm#23]

**Comment by chrisss404** [comment]
Hi Kruemmelspalter,

sorry, I don't know HypriotOS and therefore I can not answer your question. As it is stated in the Readme the pre-built packages are targeting Raspberry Pi OS. If you want to install Checkmk to a different OS you should consider building it yourself.

However, maybe you are lucky and HypriotOS has a similar base as Raspberry Pi OS (which I don't know) and it just works.

HTH & BR
Christian
