### ISSUE TITLE
No armhf architecture .deb file exists via ../check-mk-arm/releases/latest

### ISSUE THREAD

**Issue by 0phoi5** [chrisss404/check-mk-arm#30]
Your instructions advise to download the latest armhf architecture .deb file using the below command.
However, that file does not exist. There is only an arm64 file in that location, which does not match the architecture of the RPi3.

curl -LO $(curl -s https://api.github.com/repos/chrisss404/check-mk-arm/releases/latest | grep browser_download_url | cut -d '"' -f 4 | grep buster_armhf.deb)

**Comment by 0phoi5** [comment]
Your other links are now incorrect too. Where it says this...

Latest pre-built packages
Checkmk 1.6.0 for Raspberry Pi OS (32-bit) Buster: latest

... the link actually leads to the 2.0.0 version of CMK, not Buster 1.6.

**Comment by 0phoi5** [comment]
Managed to find the correct file via https://github.com/chrisss404/check-mk-arm/releases/tag/1.6.0p22

**Comment by chrisss404** [comment]
Thanks for reporting. Updated Readme.
