### ISSUE TITLE
Checkmk 2.0.0 for Ubuntu 20.10 (64-bit) Groovy .... on Raspberry PI4 with  GNU/Linux 10 (buster) (5.10.17-v8+)

### ISSUE THREAD

**Issue by ZXCloud** [chrisss404/check-mk-arm#31]
Hello all,

I have installed the above Linux on my RaspBerry PI 4 and the system itself runs in 64bit mode.

My question now would be whether this 2.0 - version of CheckMK under UBUNTU would also work umter my Linux - version or not?

Kind regards

**Comment by chrisss404** [comment]
Hi ZXCloud,

no, this version won't work for you. 

BR
Christian
