### ISSUE TITLE
Unable to parse Autocheck after Update from 1.6 to 2.0

### ISSUE THREAD

**Issue by Tibii73** [chrisss404/check-mk-arm#32]
Hello,

I have the problem that for several hosts the same issue appeared and now they where UNKNOWN in Check_MK.

![grafik](https://user-images.githubusercontent.com/81633409/113003140-ba21ab00-9172-11eb-8699-7fcfd5075c59.png)

The Agent can be found:

![grafik](https://user-images.githubusercontent.com/81633409/113003354-f05f2a80-9172-11eb-9c7e-3bafc8034e3c.png)

When I switch to the services the same error message with unable to parse autocheck appears.

I really don´t know what causes the problem. Can anyone please help me?

Best Regards,

Tim

**Comment by chrisss404** [comment]
Hi Tim,

sorry I can not help you with this issue, I have never experienced anything similar. I would advise you to ask in the [Checkmk forum](https://forum.checkmk.com), I think you could get better answers there. 

[This issue](https://forum.checkmk.com/t/not-able-to-activate-changes/18998/5) may be related, or at least it contains a similar error message. 

HTH & BR
Christian

**Comment by Asepsis** [comment]
@Tibii73 I got the same error. Maybe check the String in line 6, I had an number like 10000000L, I removed the "L" and it worked.
Hope this helps you!

BR

**Comment by Tibii73** [comment]
> 
> 
> @Tibii73 I got the same error. Maybe check the String in line 6, I had an number like 10000000L, I removed the "L" and it worked.
> Hope this helps you!
> 
> BR

Hello Aspesis,

thanks for your tip!
I removed the 'L' in every *.mk file and now every host has a similar error like this:

Error running automation call try-inventory (exit code 2), error:

Name 'diskstat_default_levels' is not defined in an autocheck entry of host 'HOSTNAME' (/omd/sites/sse/var/check_mk/autochecks/HOSTNAME.mk). This entry is in pre Checkmk 1.7 format and needs to be converted. This is normally done by "cmk-update-config -v" during "omd update". Please execute "cmk-update-config -v" for converting the old configuration.

I can´t run cmk-update-config -v. Everytime I try this I get the error: command not found.

BR

TIm

**Comment by chrisss404** [comment]
It's strange that the update script wasn't executed for you. Did you run `omd update yoursite` when you upgraded from 1.6 to 2.0?

You can try the following to run `cmk-update-config`:
```
# su yoursite
OMD[yoursite]:~$ cmk-update-config -v
```

For your site it would be:
```
# su sse
OMD[sse]:~$ cmk-update-config -v
```

**Comment by Tibii73** [comment]
> 
> 
> It's strange that the update script wasn't executed for you. Did you run `omd update yoursite` when you upgraded from 1.6 to 2.0?
> 
> You can try the following to run `cmk-update-config`:
> 
> ```
> # su yoursite
> OMD[yoursite]:~$ cmk-update-config -v
> ```
> 
> For your site it would be:
> 
> ```
> # su sse
> OMD[sse]:~$ cmk-update-config -v
> ```

Hello Chris,

thanks for you help!
I didnt know I need to log on with the user from the site. I tried it with the root user.
Now everything is working fine.
Thanks all for you help!

BR

Tim
