### ISSUE TITLE
Could I use Checkmk 2.0.0p1 for Raspberry Pi OS Buster (armhf) on RPi 4?

### ISSUE THREAD

**Issue by Tronde** [chrisss404/check-mk-arm#33]
Hi, I'm going to install the current `2021-03-04-raspios-buster-armhf` on a RPi 4 with 8 GB RAM. Your README mentions:

> Raspberry Pi OS (formerly Raspbian) "Buster" (armhf) on a RPi 3

Would this DEB be usable on RPi 4, too?

**Comment by chrisss404** [comment]
Yes, it should work on a RPi4 too.

**Comment by Tronde** [comment]
Thanks for your reply.

I've successfully installed the DEB package on:

```
Raspberry Pi 4 Model B Rev 1.4
Raspbian GNU/Linux 10 (buster)
kernel 5.10.17-v7l+
```
