### ISSUE TITLE
/usr/bin/gdebi:113: FutureWarning: Possible nested set at position 1

### ISSUE THREAD

**Issue by sergiodadi** [chrisss404/check-mk-arm#35]
Hi,

for information  (update worked) :

on Rasbperry 

[•••]
gdebi check-mk-raw-2.0.0p2_0.buster_armhf.deb 
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done

Checkmk - Best-in-class infrastructure & application monitoring
Voulez-vous installer le paquet logiciel ? [o/N] :o
**/usr/bin/gdebi:113: FutureWarning: Possible nested set at position 1
  c = findall("[[(](\S+)/\S+[])]", msg)[0].lower()**
Sélection du paquet check-mk-raw-2.0.0p2 précédemment désélectionné.
[...]

My OS:

lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

thank for your work 

Serge

**Comment by chrisss404** [comment]
Hi Serge,

thanks for reporting. However, it seems that this warning is unrelated to checkmk. Here is a similar issue installing a deb package with gdebi: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=926633

BR
Christian
