### ISSUE TITLE
[ARM64/ M1] Error starting Nagios & other services

### ISSUE THREAD

**Issue by bjerrecs** [chrisss404/check-mk-arm#39]
**Hi!**

Sorry for bothering this repo with this question.
I'm trying to run the CheckMk monitoring on my Macbook Pro with an M1 CPU.

Since it's arm-based I thought that the docker image that you guys have made would work.
But I'm getting some errors that I can share a couple of screenshots of.

I use checkmk for my work and would like a "demo" environment locally for testing new stuff.

I'm up for sharing logs and help all that I can to get this to work.

Thanks in advance!
Br. Simon
![image](https://user-images.githubusercontent.com/32055984/123084582-998b8900-d421-11eb-956c-a9ead5a9d4e7.png)
![image](https://user-images.githubusercontent.com/32055984/123084592-9c867980-d421-11eb-8ba3-ab94f0e18eca.png)

**Comment by chrisss404** [comment]
Hey there,

I guess you came to the wrong place. This repository neither supports a docker image nor binaries targeting Apple's ARM CPUs.

However, you can try compiling binaries for your platform yourself. It should work quite similar to what is done for the raspberry pis.

BR
Christian
