### ISSUE TITLE
Missing armv7l_linux.mk

### ISSUE THREAD

**Issue by makanakoeln** [chrisss404/check-mk-arm#4]
I get:

make[3]: armv7l_linux.mk: Datei oder Verzeichnis nicht gefunden
make[3]: *** Keine Regel, um �armv7l_linux.mk� zu erstellen.  Schluss.     make[3]: Verzeichnis �/home/pi/make_check_mk/check-mk-raw-1.4.0p21.cre/packages/snap7/snap7-full-1.3.0/build/unix� wird verlassen
Makefile:23: die Regel f�r Ziel �build� scheiterte
make[2]: *** [build] Fehler 2
make[2]: Verzeichnis �/home/pi/make_check_mk/check-mk-raw-1.4.0p21.cre/packages/snap7� wird verlassen
Makefile:83: die Regel f�r Ziel �build� scheiterte                         make[1]: *** [build] Fehler 2                                              make[1]: Verzeichnis �/home/pi/make_check_mk/check-mk-raw-1.4.0p21.cre� wird verlassen
debian/rules:24: die Regel f�r Ziel �build-stamp� scheiterte
make: *** [build-stamp] Fehler 2
dpkg-buildpackage: Fehler: Fehler-Exitstatus von debian/rules build war 2

Any idea?

Thx!

**Comment by makanakoeln** [comment]
Think i found a solution. Did i miss something or is that patch missing?

**Comment by flix87** [comment]
Look here:
https://github.com/chrisss404/check-mk-arm/issues/2

**Comment by makanakoeln** [comment]
Works for me, thanks!
