### ISSUE TITLE
Download check-mk-raw-1.4.0p21_0.stretch_armhf.deb

### ISSUE THREAD

**Issue by Lonerider2010** [chrisss404/check-mk-arm#5]
Where do I get it? It is not available at [http://mathias-kettner.com/check_mk_download_version.php?HTML=yes&version=1.4.0p33&edition=cre](url).

**Comment by chrisss404** [comment]
The build script is not tested with jessie, currently I run it only with stretch, so you might run into some issues.

First, there are issues installing the required dependencies, as can be seen here:

    138 MB an Archiven müssen heruntergeladen werden. Nach dem Entpacken werden 425 MB zusätzlich belegt sein.
    E: Konnte Sperre /var/cache/apt/archives/lock nicht bekommen - open (11: Die Ressource ist zur Zeit nicht verfügbar)
    E: Das Verzeichnis /var/cache/apt/archives/ kann nicht gesperrt werden.
    ERROR. Some packages could not be installed. You will get 
    Problems while compiling if something is missing.

Secondly, one of the patches can not be applied, as can be seen here:

    patching file packages/perl-modules/lib/BuildHelper.pm
    patching file Makefile
    patching file packages/nrpe/Makefile
    Hunk #1 FAILED at 17.
    1 out of 1 hunk FAILED -- saving rejects to file packages/nrpe/Makefile.rej

If you just want to download and test Check_MK on your RaspberryPI, you can get the latest packages from the [release page](https://github.com/chrisss404/check-mk-arm/releases).
