### ISSUE TITLE
Can't install .deb on Ubuntu 22.04 VM, MacBook M1

### ISSUE THREAD

**Issue by sticsk** [chrisss404/check-mk-arm#50]
When doing `dpkg -i` on the deb file, i get the dependency error. 

This is the error when I execute `apt-get install -f`

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED:
  check-mk-raw-2.0.0p24
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 541 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 183744 files and directories currently installed.)
Removing check-mk-raw-2.0.0p24 (0.impish) ...
needrestart is being skipped since dpkg has failed```

**Comment by martux69** [comment]
Til now there is no deb version available for Ubuntu 22.04 and it is not possible to use the version from 20.04.


-----Ursprüngliche Nachricht-----

**Comment by sticsk** [comment]
I understand then, I tought's working anyways. Thank you

**Comment by martux69** [comment]
@sticsk : I added the actual version 2.0.0.p25 of checkmk for Ubuntu 22.04, which was released yesterday. Til now it is untested, feel free to try it.
