### ISSUE TITLE
New checkmk version 2.1.0p…

### ISSUE THREAD

**Issue by chbally** [chrisss404/check-mk-arm#51]
Hey,
appreciate the great work you are doing.
How about the new version 2.1.0p…
Are you going to provide that und check-me-arm as well?
Would make me very happy.
Yours

**Comment by martux69** [comment]
I'm just working on the build of the arm64 version of 2.1.0, it is only a matter of time, but it will come ;-)

**Comment by chbally** [comment]
Thanks a lot!
Locking forward.

**Comment by chrisss404** [comment]
@chbally added 2.1.0 targeting Raspberry Pi OS (32-bit) "Bullseye"

@martux69 added and updated the patches that were needed in `build_check_mk_bullseye32.sh` to
`build_check_mk_groovy64.sh`. I hope they work for you as well. Additionally, I had to install the following dev packages: `freetds-dev`, `libsasl2-dev`, `libsodium-dev`, `patchelf`, and `python3-pip`.

The main branch now contains the build scripts for 2.1.0, for version 2.0.0 please refer to this branch: https://github.com/chrisss404/check-mk-arm/tree/2.0.0

**Comment by martux69** [comment]
arm64 for jammy is now available, I'm still working on focal.

**Comment by chrisss404** [comment]
I'll close this as versions of 2.1.0p are available.
