### ISSUE TITLE
checkmk auf Oracle Cloud Arm

### ISSUE THREAD

**Issue by mathschut** [chrisss404/check-mk-arm#53]
Hi, ist es möglich das CheckMK von dir auch unter Ubuntu ARM in der Oracle Free Cloud Infra laufen zu lassen oder geht das nur unter Raspi Arm?

**Comment by mathschut** [comment]
Hi, danke für die Infos. Es läuft alles super, danke dir.

**Comment by lorivaro** [comment]
Hi, I have followed these steps on my Oracle Cloud instance using 2.1.0p24 (2.1.0p25 wasn't built somehow), as I'd like to monitor this server from elsewhere. 
However, I can't seem to use the `cmk-agent-ctl` command to register this server. 
Is there a way I could using this build, or am I in the wrong place?
