### ISSUE TITLE
armv7 - ubuntu:jammy

### ISSUE THREAD

**Issue by JzJad** [chrisss404/check-mk-arm#54]
Was wondering if you could possibly add a armv7 package for ubuntu:jammy. Not required or anything it would just be nice to have so that I can package multi-arch together as I'm currently building 2 images for armv7/armv8 (bullseye/ubuntu)

Thanks for the work you have already done! 😄

**Comment by chrisss404** [comment]
Hi Jimmy,

currently I have no plans to add more packages. 

However, it should be fairly easy to compile the package yourself in your docker container.  You only have to add the `omdlib-reduce-certificate-maximum-validity-period` patch and replace the `python-make-set-aarch64-architecture` with the `python-make-set-arm-architecture` patch in `build_check_mk_ubuntu_64bit.sh`.

#### Note to myself:

To build _arm64_ images on _amd64_, ensure that `qemu-user-static` is available, then:
```
# Dockerfile
FROM ubuntu:jammy

RUN dpkg --print-architecture # should print arm64
```
```
$ docker buildx build --platform linux/arm64 --progress plain --no-cache -t checkmk .
```


Good luck & BR
Christian

**Comment by JzJad** [comment]
Awesome thanks for the quick tips that should make for a quick an easy solution for me to put together!

Kind Regards,
Jimmy
