### ISSUE TITLE
check-mk-raw-2.1.0p25_0.bullseye_arm64.deb on Rasbian OS 64bit

### ISSUE THREAD

**Issue by jkehrel** [chrisss404/check-mk-arm#56]
Not an issue but positive feedback. Debian check-mk-raw-2.1.0p25_0.bullseye_arm64.deb runs without any problems or changes on my Rapsbery Pi 4 with 4GB RAM on Rasbian OS 64bit  kernel 5.15.84-v8+.
Thanks for your work.

**Comment by chrisss404** [comment]
Thank you for letting us know. Shout out to @martux69 for making this happen!
