### ISSUE TITLE
Cannot modify notification rules

### ISSUE THREAD

**Issue by speridal** [chrisss404/check-mk-arm#9]
Hi there,

I have a problem editing the notification rules. If I try to create a new one or edit an existing I cannot click the save button at the bottom of the page. 
I already cleared the browser caches and tried to use different browser with no success.

Do you have an idea?

Best regards,
Bernd

**Comment by chrisss404** [comment]
Hi Bernd,

this works fine for me using the classic theme in version 1.5.0p16.

What do you mean by you can not click the save button?
Is there a page load after you click the button? 
Can you see that a request is triggered?
Have you checked the logs?

Sorry, I could not help you, but you have not provided much information.

BR
Christian
